import { StyleSheet } from 'react-native';
import { st, Mcolor, deviceW, Bcolor } from '../../utils';

const swiperHeight = (deviceW - 20) * 0.3;
const styles = StyleSheet.create({
  ...st,
  headerNavigation: {
    backgroundColor: '#fff',
    marginTop: -20,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
    position: 'relative',
    zIndex: 999,
    height: 100,
    ...st.frcenter,
  },
  titleViewIcon: {
    fontSize: 22,
    marginRight: 6,
    color: Bcolor,
  },
  headerNavigationText: {
    fontSize: 13,
    color: '#333',
    marginTop: 3,
  },
  navImg: {
    width: 40,
    height: 40,
    marginBottom: 6,
  },
  mainIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    ...st.jacenter,
    marginBottom: 6,
  },
  mainIconFont: {
    fontSize: 34,
    fontWeight: 'bold',
    color: '#fff',
  },
  SampleCenterText: {
    fontSize: 14,
    color: '#444',
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  flexOne: {
    flex: 1,
  },
  flexTwo: {
    flex: 2,
    paddingLeft: 10,
  },
  textCenter: {
    textAlign: 'center',
  },
  gong: {
    fontSize: 30,
    color: '#53E0B5',
    textAlign: 'center',
  },
  hang: {
    fontSize: 30,
    color: '#FAC342',
    textAlign: 'center',
  },
  hui: {
    fontSize: 30,
    marginLeft: 5,
    textAlign: 'center',
    color: '#9ED63C',
  },
  my: {
    fontSize: 30,
    marginTop: 2,
    textAlign: 'center',
    color: '#82B4FD',
  },
  normalThressText: {
    color: '#333',
    fontSize: 14,
  },
  normalSixText: {
    color: '#666',
    fontSize: 14,
  },
  normalNineText: {
    color: '#999',
    fontSize: 14,
  },
  goodsType: {
    marginLeft: 10,
    marginRight: 10,
    paddingTop: 15,
    marginBottom: 10,
    height: 180,
    borderRadius: 6,
    backgroundColor: '#fff',
  },
  goodsTypeIcn: {
    fontSize: 30,
    textAlign: 'center',
    marginBottom: 4,
  },
  goodsTypeText: {
    fontSize: 13,
    color: '#333',
    marginTop: 5,
    marginBottom: 15,
  },
  goodsTypeOne: {
    width: '25%',
    ...st.jacenter,
  },
  goodsTypeOne2: {
    ...st.jacenter,
  },
  goodsTypeOneWidth: {
    width: '25%',
  },
  goodsTypeOneWidthFlexOne: {
    flex: 1,
  },
  icnBoxOne: {
    width: 50,
    height: 50,
    flexDirection: 'row',
    alignSelf: 'center',
    marginBottom: 10,
  },
  icnBoxTwo: {
    width: 44,
    height: 44,
    ...st.jacenter,
    backgroundColor: '#F4F6FF',
    marginBottom: 5,
    borderRadius: 22,
  },
  icnBoxImg: {
    width: 32,
    height: 32,
  },
  SampleCenter: {
    ...st.fr,
    marginLeft: 10,
    marginBottom: 10,
    justifyContent: 'space-between',
    ...st.acenter,
  },
  SampleCenterList: {
    flex: 1,
    ...st.jacenter,
    padding: 10,
    borderRadius: 6,
    backgroundColor: '#fff',
    marginRight: 10,
  },
  sampleImg: {
    width: '100%',
    height: 70,
    marginBottom: 6,
  },
  SampleCenterBorder: {
    borderLeftWidth: 1,
    borderLeftColor: '#eee',
    paddingTop: 10,
    paddingBottom: 10,
  },
  SampleCenterTitle: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
  },
  SampleCenterLabel: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
  },
  SampleCenterIcn: {
    marginTop: 5,
    textAlign: 'center',
    fontSize: 80,
  },
  seasonalGoodsBox: {
    ...st.fr,
    backgroundColor: '#fff',
    marginLeft: 10,
    marginRight: 10,
    flexWrap: 'wrap',
  },
  sgView: {
    minWidth: '42%',
    flex: 1,
    height: 160,
  },
  sgBigImg: {
    position: 'absolute',
    width: '100%',
    height: 160,
  },
  sgViewText: {
    position: 'relative',
    padding: 5,
  },
  sgViewText1: {
    fontSize: 18,
    color: '#5C9AE5',
    marginBottom: 6,
    backgroundColor: 'transparent',
  },
  sgViewText2: {
    fontSize: 12,
    backgroundColor: 'transparent',
    color: '#333',
  },
  sgViewRight: {
    borderRightColor: '#eee',
    borderRightWidth: 1,
  },
  sgItemsBtn: {
    minWidth: '42%',
    flex: 1,
    height: 80,
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    backgroundColor: '#fff',
  },
  sgItems: {
    flex: 1,
    height: 90,
    ...st.frcenter,
  },
  sgImgView: {
    width: 60,
    height: 60,
    backgroundColor: '#EEF9FF',
    borderRadius: 30,
    ...st.jacenter,
    marginRight: 10,
  },
  sgImg: {
    width: 40,
    height: 40,
  },
  sgItemText: {
    paddingLeft: 10,
    flex: 1,
  },
  sgItemText1: {
    fontSize: 16,
    backgroundColor: 'transparent',
    color: '#333',
    marginBottom: 6,
  },
  sgItemText2: {
    fontSize: 12,
    backgroundColor: 'transparent',
    color: '#999',
  },
  seasonalGoodsItem: {
    borderTopWidth: 1,
    borderTopColor: '#eee',
    borderRightWidth: 1,
    borderRightColor: '#eee',
    paddingTop: 4,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 5,
  },
  seasonalGoodsLabel: {
    fontSize: 14,
    color: '#999',
  },
  imageBox: {
    width: 50,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 15,
  },
  image: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginTop: 6,
  },
  slide: {
    flex: 1,
    height: swiperHeight,
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  swiperImage: {
    flex: 1,
    height: swiperHeight,
    backgroundColor: 'transparent',
  },
  forYou: {
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: '#fff',
    borderRadius: 8,
  },
  forTitleView: {
    height: 50,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    marginBottom: 6,
    ...st.frcenter,
  },
  forTitleImg: {
    width: 30,
    height: 30,
    marginRight: 10,
  },
  forTitle: {
    fontSize: 18,
    color: Bcolor,
  },
  bomFixedView: {
    height: 0,
    position: 'relative',
  },
  bomFixedBtn: {
    width: 50,
    height: 50,
    overflow: 'hidden',
    backgroundColor: Mcolor,
    position: 'absolute',
    right: 10,
    bottom: 40,
    borderRadius: 25,
    ...st.jacenter,
  },
  bomFixedText: {
    fontSize: 14,
    color: '#fff',
  },
  fristBox: {
    width: 60,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    borderRadius: 30,
  },
  myImage: {
    flex: 1,
    height: 80,
    borderRadius: 40,
    marginTop: 5,
  },
  textBorder: {
    borderBottomWidth: 2,
    borderBottomColor: '#8BCE21',
  },
  tabText: {
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
  },
  tabTextChoose: {
    color: '#8BCE21',
  },
  headerImgBox: {
  },
  headerImg: {
    height: deviceW * 0.3,
    width: deviceW,
  },
  boxStyle: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    marginTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 4,
  },
  headerText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    marginTop: 80,
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
  },
  inputText: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: 40,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 8,
    paddingRight: 8,
  },
  headerIcn: {
    fontSize: 18,
    color: '#666',
  },
  swiperWrapper: {
    margin: 10,
    borderRadius: 8,
    overflow: 'hidden',
  },
});
export default styles;
