export const LOGIN_UPDATE = 'LOGIN_UPDATE';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
export const COMMON_ERROR = 'COMMON_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOADING_SLEEK_SHOW = 'LOADING_SLEEK_SHOW';
export const LOADING_SLEEK_HIDE = 'LOADING_SLEEK_HIDE';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_CLEAR = 'EMPLOYEE_CLEAR';
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS';

export const TEXT_UPDATE = 'TEXT_UPDATE';
export const TEXT_CLEAR = 'TEXT_CLEAR';
