import { StyleSheet } from 'react-native';
import { st, Mcolor } from '../../utils';

const styles = StyleSheet.create({
  flexRowBox: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  goodsInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
  },
  goodsImg: {
    width: 80,
    height: 80,
    marginLeft: 10,
    marginTop: 5,
    marginBottom: 5,
  },
  goodsNameBox: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#F8F8F8',
    paddingLeft: 10,
    paddingRight: 10,
    height: 80,
  },
  totalBox: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
  },
  footerBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  btnBox: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginLeft: 10,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  btnBox1: {
    height: 30,
    width: 60,
    ...st.jacenter,
    borderWidth: 1,
    borderColor: Mcolor,
    backgroundColor: Mcolor,
    borderRadius: 15,
    marginLeft: 10,
  },
});
export default styles;
