import { StyleSheet } from 'react-native';
// import { Mgreen, st } from '../../utils';

const styles = StyleSheet.create({
  goodsDetail: {
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    backgroundColor: '#fff',
  },
  goodsDetail2: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    backgroundColor: '#fff',
  },
  goodsPrice: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  readPeople: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  renovateTime: {
    flex: 1,
    textAlign: 'right',
    color: '#666',
    fontSize: 14,
  },
  btnList: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
  },
  btnBox: {
    paddingLeft: 8,
    paddingRight: 8,
    paddingTop: 7,
    paddingBottom: 7,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginLeft: 8,
  },
  btnText: {
    fontSize: 14,
    color: '#333',
  },
  btnChoose: {
    backgroundColor: '#FC8521',
  },
  btnTextChoose: {
    color: '#fff',
  },
  activeDetail: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  otherIndustryBox: {
    minHeight: 15,
    maxHeight: 15,
    backgroundColor: '#61BC3F',
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 3,
    marginBottom: 6,
  },
  otherIndustry: {
    color: '#fff',
    fontSize: 9,
    textAlign: 'center',
  },
  time: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  everyWeek: {
    color: '#FF7F12',
    borderWidth: 1,
    borderColor: '#FF7F12',
    borderRadius: 3,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 8,
    paddingRight: 8,
    fontSize: 9,
    marginRight: 10,
  },
  scaleText: {
    color: '#666',
    fontSize: 11,
  },
  offerBox: {
    borderColor: '#FF7F12',
    borderWidth: 1,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 3,
  },
  offer: {
    fontSize: 16,
    color: '#FF7F12',
    textAlign: 'center',
  },
  buyTime: {
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    backgroundColor: '#F5F5F5',
  },
  buyTimeText: {
    color: '#666',
    fontSize: 14,
  },
  goodsImg: {
    width: 100,
    height: 100,
    marginRight: 10,
  },
  goodsInfoDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  goodsName: {
    fontSize: 14,
    color: '#333',
    marginBottom: 8,
  },
  price: {
    color: '#FF7F12',
    fontSize: 16,
    marginBottom: 6,
  },
  address: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  addressText: {
    fontSize: 14,
    color: '#666',
  },
  label: {
    flexDirection: 'row',
  },
  labelText: {
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    borderWidth: 1,
    borderColor: '#FF7F12',
    color: '#999',
  },
  yw: {
    color: '#666',
    fontSize: 14,
    marginBottom: 4,
  },
  userAddress: {
  },
  userName: {
    fontSize: 16,
    color: '#333',
    marginBottom: 8,
  },
  userImg: {
    width: 80,
    height: 80,
    marginRight: 10,
  },
  userInfoDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  exampleImg: {
    width: 120,
    height: 120,
    marginRight: 10,
  },
  gyTitle: {
    fontSize: 18,
    color: '#333',
    alignSelf: 'flex-start',
    // marginBottom: 15,
  },
  gyPrice: {
    fontSize: 20,
    color: '#FC8521',
    marginBottom: 4,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  aa: {
    color: '#666',
    fontSize: 14,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    borderWidth: 1,
    borderColor: '#FC8521',
    marginRight: 4,
    marginBottom: 2,
  },
  name: {
    flex: 1,
    fontSize: 18,
    color: '#333',
  },
  UserYw: {
    flex: 1,
    fontSize: 14,
    color: '#666',
  },
  logoImg: {
    width: 18,
    height: 18,
    marginRight: 4,
  },
});
export default styles;
