import { StyleSheet, Dimensions } from 'react-native';
import { st, Mcolor, deviceW } from '../../utils';

const { width } = Dimensions.get('window');
const styles = StyleSheet.create({
  headerImgBox: {
    // marginTop: 2,
  },
  headerImg: {
    height: deviceW * 0.3,
    width: '100%',
  },
  headerText: {
    textAlign: 'center',
    backgroundColor: 'transparent',
    marginTop: 80,
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
  },
  boxStyle: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    marginTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 4,
  },
  headerIcn: {
    fontSize: 18,
    color: '#666',
  },
  inputText: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: 40,
    paddingTop: 0,
    paddingBottom: 0,
  },
  headerNavigation: {
    paddingTop: 20,
    marginTop: 4,
    paddingBottom: 20,
    backgroundColor: '#fff',
  },
  headerNavigationTwo: {
    paddingTop: 10,
    paddingBottom: 20,
    backgroundColor: '#fff',
  },
  goodsTypeTitle: {
    fontSize: 16,
    color: '#333',
    paddingTop: 10,
    textAlign: 'center',
  },
  goodsType: {
    marginTop: 5,
    backgroundColor: '#fff',
  },
  headerNavigationText: {
    fontSize: 13,
    marginTop: 3,
    color: '#333',
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  normalThreeText: {
    fontSize: 14,
    color: '#666',
  },
  flexOne: {
    flex: 1,
  },
  mainIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    ...st.jacenter,
    marginBottom: 6,
  },
  mainIconTwo: {
    width: 50,
    height: 50,
    borderRadius: 25,
    ...st.jacenter,
    marginBottom: 6,
  },
  mainIconFont: {
    fontSize: 34,
    color: '#fff',
  },
  mainIconFontSecend: {
    fontSize: 26,
    color: '#fff',
  },
  flexTwo: {
    flex: 2,
    paddingLeft: 10,
  },
  textCenter: {
    textAlign: 'center',
  },
  gong: {
    fontSize: 40,
    color: '#fff',
    textAlign: 'center',
  },
  hang: {
    fontSize: 40,
    color: '#fff',
    textAlign: 'center',
  },
  hui: {
    fontSize: 36,
    marginLeft: 5,
    textAlign: 'center',
    color: '#fff',
  },
  my: {
    fontSize: 40,
    marginTop: 2,
    textAlign: 'center',
    color: '#fff',
  },
  publicIcn: {
    marginBottom: 6,
    fontSize: 60,
  },
  normalThressText: {
    color: '#333',
    fontSize: 14,
  },
  normalSixText: {
    color: '#666',
    fontSize: 14,
  },
  normalNineText: {
    color: '#999',
    fontSize: 14,
  },
  seller: {
    marginTop: 10,
    backgroundColor: '#fff',
    flexDirection: 'row',
  },
  flexfive: {
    flex: 5,
    borderRightWidth: 1,
    borderRightColor: '#eee',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  flexfour: {
    flex: 4,
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#eee',
  },
  icnImg: {
    height: 50,
    width: 50,
    marginTop: 4,
    marginBottom: 4,
  },
  bigTitle: {
    fontSize: 20,
    color: '#333',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  imgBox: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  BigIcnImg: {
    width: 100,
    height: 100,
  },
  bottomBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  bigThreeText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 4,
  },
  news: {
    backgroundColor: '#fff',
    marginTop: 5,
    paddingLeft: 10,
    paddingRight: 10,
  },
  newsImgView: {
    width: 60,
    height: 60,
    marginRight: 10,
  },
  goodsImg: {
    width: 60,
    height: 60,
  },
  rowBox: {
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    paddingTop: 10,
    paddingBottom: 10,
  },
  goodsTitle: {
    color: '#333',
    fontSize: 18,
    marginBottom: 8,
  },
  studyBox: {
    backgroundColor: '#fff',
    marginTop: 3,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  leftText: {
    width: 40,
    fontSize: 16,
    color: '#67BC46',
    marginRight: 6,
  },
  centerText: {
    width: 40,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FC8521',
    marginRight: 6,
  },
  studyRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  slide: {
    height: 150,
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  swiperImage: {
    width,
    height: 150,
    backgroundColor: 'transparent',
    resizeMode: 'stretch',
  },
  howMuchPeople: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
    paddingBottom: 10,
  },
  people: {
    fontSize: 16,
    color: '#666',
  },
  buyGoodsItem: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
    marginBottom: 3,
  },
  itemNameLine: {
    ...st.fr,
    ...st.acenter,
    height: 24,
  },
  buyGoodsName: {
    fontSize: 16,
    color: '#333',
  },
  buyGoodsVariety: {
    flex: 1,
    marginLeft: 4,
    fontSize: 13,
    color: '#666',
  },
  flexRight: {
    flex: 1,
    textAlign: 'right',
    color: '#FC8521',
    fontSize: 14,
  },
  buyGoodsPlace: {
    flex: 1,
    color: '#666',
    fontSize: 14,
  },
  goBuyBtnBox: {
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#FC8521',
    borderRadius: 5,
  },
  goBuyBtn: {
    color: '#fff',
    fontSize: 16,
  },
  userDoBigBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userDoBox: {
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    backgroundColor: '#67BC46',
    borderRadius: 2,
  },
  userDo: {
    fontSize: 12,
    color: '#fff',
  },
  everyWeekBox: {
    borderWidth: 0.6,
    borderColor: '#FC8521',
    borderRadius: 2,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    marginRight: 4,
  },
  everyWeek: {
    fontSize: 12,
    color: '#FC8521',
  },
  howLong: {
    fontSize: 12,
    color: '#666',
  },
  howLongDay: {
    fontSize: 12,
    color: Mcolor,
  },
  bomFixedView: {
    height: 0,
    position: 'relative',
  },
  bomFixedBtn: {
    width: 50,
    height: 50,
    overflow: 'hidden',
    backgroundColor: Mcolor,
    position: 'absolute',
    right: 10,
    bottom: 40,
    borderRadius: 25,
    ...st.jacenter,
  },
  bomFixedText: {
    fontSize: 14,
    color: '#fff',
  },
  fristBox: {
    width: 60,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    borderRadius: 30,
  },
  forYouText: {
    flex: 1,
    fontSize: 14,
    color: Mcolor,
    textAlign: 'center',
    paddingBottom: 10,
    paddingTop: 10,
    marginBottom: 1,
    backgroundColor: '#fff',
  },
});
export default styles;
