import { StyleSheet } from 'react-native';
import { st, Mcolor, Mred } from '../../utils';

const styles = StyleSheet.create({
  topPart: {
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 25,
    backgroundColor: '#fff',
  },
  userImg: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 10,
  },
  QRCode: {
    width: 70,
    height: 70,
  },
  fotBtn1: {
    flex: 0.5,
    backgroundColor: '#fff',
    ...st.jacenter,
  },
  fotChatIcon: {
    color: '#666',
    marginRight: 8,
    fontSize: 14,
  },
  fotChatText: {
    color: '#666',
    fontSize: 14,
  },
  fotChatText1: {
    color: Mred,
    fontSize: 14,
  },
  topIcon1: {
    color: Mred,
  },
  fotBtn2: {
    flex: 1,
    backgroundColor: Mcolor,
    ...st.jacenter,
  },
  fotText: {
    color: '#fff',
    fontSize: 14,
  },
  name: {
    color: '#333',
    fontSize: 14,
    marginBottom: 10,
  },
  nameReal: {
    marginTop: 4,
    color: '#999',
    fontSize: 14,
    marginBottom: 10,
  },
  aa: {
    color: '#666',
    fontSize: 11,
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    borderWidth: 1,
    borderRadius: 3,
    marginRight: 4,
    marginBottom: 2,
  },
  status: {
    color: '#666',
    fontSize: 14,
  },
  isAccreditation: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  leftPart: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  myBusiness: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    marginTop: 10,
  },
  accreditationBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  accreditationText: {
    color: '#666',
    fontSize: 14,
    marginLeft: 5,
  },
  RightPart: {
    textAlign: 'right',
    marginLeft: 10,
  },
  flexBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  flexOneTextLeft: {
    flex: 1,
    color: '#666',
    fontSize: 14,
  },
  tabView: {
    height: 50,
    flex: 1,
    backgroundColor: '#fff',
    ...st.jacenter,
    borderBottomWidth: 2,
    borderBottomColor: '#fff',
  },
  flexOne: {
    flex: 1,
  },
  flexOneTextRight: {
    flex: 1,
    color: '#666',
    fontSize: 14,
    textAlign: 'right',
  },
  goodsDetail: {
    marginLeft: 10,
    marginRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    borderWidth: 1,
  },
  goodsPrice: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  type: {
    marginTop: 10,
  },
  goodsItem: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  goodsImg: {
    width: 80,
    height: 80,
    marginRight: 10,
  },
  goodsName: {
    fontSize: 14,
    color: '#333',
    marginBottom: 6,
  },
  goodsPlace: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  chooseBtn: {
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 4,
    paddingRight: 4,
    fontSize: 12,
    color: '#666',
    borderWidth: 1,
    borderColor: '#FC8521',
    marginBottom: 50,
  },
  goodsPriceInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  price: {
    fontSize: 16,
    color: '#FC8521',
    marginRight: 4,
  },
  yuan: {
    fontSize: 12,
    color: '#FC8521',
  },
  howLongBox: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  howLong: {
    fontSize: 12,
    color: '#666',
  },
  buyGoodsItem: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  buyGoodsName: {
    fontSize: 16,
    color: '#333',
    marginBottom: 4,
  },
  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  flexRight: {
    flex: 1,
    textAlign: 'right',
    color: '#FC8521',
    fontSize: 14,
  },
  buyGoodsVariety: {
    fontSize: 14,
    color: '#666',
  },
  buyGoodsPlace: {
    marginTop: 4,
    color: '#666',
    fontSize: 14,
  },
  goBuyBtnBox: {
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#FC8521',
    borderRadius: 5,
  },
  goBuyBtn: {
    color: '#fff',
    fontSize: 16,
  },
  hiddenBox: {
    backgroundColor: '#fff',
    borderWidth: 1,
  },
  ycBox: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  hiddenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  container: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  maskerContent: {
    paddingLeft: 10,
    paddingRight: 10,
  },
  row: {
    paddingTop: 15,
    paddingBottom: 15,
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
  },
  circle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4BBE28',
    marginRight: 10,
    marginTop: 4,
  },
  listTitle: {
    fontSize: 18,
    color: '#333',
    marginBottom: 4,
  },
  listLabel: {
    fontSize: 14,
    color: '#666',
  },
  listLabelRight: {
    fontSize: 14,
    color: '#8ECD24',
    marginLeft: 2,
  },
  textBorder: {
    borderBottomWidth: 2,
    borderBottomColor: Mcolor,
  },
  tabText: {
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
  },
  tabTextChoose: {
    color: Mcolor,
  },
});
export default styles;
