import { StyleSheet } from 'react-native';
import { st, px, Mcolor, Bcolor3, deviceW } from '../../utils';

const styles = StyleSheet.create({
  ...st,
  userView: {
    flex: 1,
    paddingLeft: 20,
    paddingBottom: 20,
    ...st.jcenter,
  },
  userText: {
    fontSize: 14,
    color: '#fff',
    backgroundColor: 'transparent',
  },
  noText: {
    color: 'transparent',
  },
  topView: {
    height: 175,
  },
  headerBackground: {
    flex: 1,
    width: deviceW,
    height: 175,
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  headerImg: {
    flex: 1,
    height: '100%',
    resizeMode: 'stretch',
  },
  firstBox: {
    marginLeft: 10,
    marginRight: 10,
  },
  backGroundImg: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    borderRadius: 5,
  },
  firstBottom: {
    height: 30,
    ...st.frcenter,
    paddingTop: 10,
    paddingLeft: 30,
    paddingRight: 30,
  },
  topMlist: {
    ...st.frcenter,
    flex: 1,
  },
  topMlistIcon: {
    fontSize: 14,
    color: '#fff',
    marginRight: 5,
    backgroundColor: 'transparent',
  },
  topMlistText: {
    fontSize: 12,
    color: '#fff',
    backgroundColor: 'transparent',
  },
  topMlistCount: {
    fontSize: 14,
    marginLeft: 4,
    fontWeight: 'bold',
    color: '#fff',
    backgroundColor: 'transparent',
  },
  firstBottomCount: {
    textAlign: 'center',
    fontSize: 18,
    backgroundColor: 'transparent',
    color: '#333',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  firstBottomCount2: {
    textAlign: 'center',
    fontSize: 18,
    backgroundColor: 'transparent',
    color: '#333',
    fontWeight: 'bold',
    marginTop: 4,
    marginBottom: 5,
  },
  firstBottomLabel: {
    flex: 1,
    textAlign: 'center',
    fontSize: 14,
    color: '#555',
    backgroundColor: 'transparent',
  },
  accountMoney: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 30,
  },
  textBackground: {
    backgroundColor: 'transparent',
    padding: 3,
    borderRadius: 3,
  },
  textSmall: {
    fontSize: 12,
    color: '#fff',
  },
  textMoney: {
    fontSize: px(22),
  },
  detailInfo: {
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 10,
    backgroundColor: '#fff',
  },
  infoBox: {
    height: 60,
    ...st.frcenter,
  },
  aa: {
    height: 60,
    ...st.frcenter,
  },
  infoBox2: {
    paddingTop: 15,
    paddingBottom: 15,
    marginBottom: 4,
  },
  myWidth: {
    width: '25%',
  },
  flexOne: {
    flex: 1,
  },
  headerImgBox: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 10,
  },
  imgBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#fff',
  },
  icnBox: {
    width: 40,
    height: 40,
    ...st.jacenter,
    borderRadius: 20,
    marginLeft: 5,
    backgroundColor: '#666',
  },
  icnBoxl: {
    width: 40,
    height: 40,
    ...st.jacenter,
    marginBottom: 5,
    borderRadius: 20,
    backgroundColor: '#666',
  },
  userImg: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 10,
  },
  myIdentity: {
    paddingTop: 15,
    paddingBottom: 15,
    color: '#666',
  },
  paddingB: {
    paddingBottom: 30,
  },
  borderB: {
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  soldList: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  soldListRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  soldListRowOne: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  border: {
    borderRightWidth: 1,
    borderRightColor: '#eee',
  },
  ModalStyle: {
    backgroundColor: '#fff',
    height: 170,
  },
  modalView: {
    flex: 1,
  },
  shareLists: {
    ...st.frcenter,
    backgroundColor: '#f8f8f8',
    height: 120,
    paddingTop: 20,
    paddingBottom: 20,
  },
  shareList: {
    flex: 1,
    ...st.acenter,
  },
  shareTop: {
    width: 50,
    height: 50,
    ...st.jacenter,
    borderRadius: 30,
    marginBottom: 10,
  },
  shareIcon: {
    fontSize: 40,
    color: '#fff',
    marginBottom: 6,
  },
  shareText: {
    fontSize: 12,
    color: '#444',
  },
  shareBtn: {
    backgroundColor: '#fff',
    borderTopColor: '#ddd',
    borderTopWidth: 1,
    height: 50,
    ...st.jacenter,
  },
  shareBtnText: {
    fontSize: 14,
    color: '#333',
  },
  displayCountBox: {
    position: 'absolute',
    left: 18,
    top: -4,
    height: 18,
    ...st.jacenter,
    borderRadius: 10,
    backgroundColor: '#ff0000',
    paddingLeft: 5,
    paddingRight: 5,
  },
  prompt: {
    width: 8,
    height: 8,
    borderRadius: 5,
    backgroundColor: '#ff0000',
    position: 'absolute',
    right: 10,
    top: 10,
  },
  myBox: {
    borderTopWidth: 1,
    borderTopColor: '#eee',
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  mmDot: {
    width: 18,
    height: 60,
    borderRadius: 6,
    backgroundColor: Mcolor,
    ...st.jacenter,
    position: 'absolute',
    top: 0,
    left: '50%',
  },
  mmDotText: {
    color: '#fff',
    fontSize: 13,
  },
  idView: {
    backgroundColor: Bcolor3,
    paddingLeft: 5,
    paddingRight: 5,
    height: 20,
    ...st.fr,
    ...st.acenter,
    marginTop: 6,
    borderRadius: 10,
  },
  saleView: {
    margin: 10,
    backgroundColor: '#fff',
    paddingTop: 10,
    paddingBottom: 10,
  },
  saleTitle: {
    borderRightColor: '#ddd',
    borderRightWidth: 1,
    paddingRight: 10,
    paddingLeft: 5,
  },
  saleIcon: {
    fontSize: 28, color: Bcolor3, marginBottom: 4,
  },
  saleText: {
    color: Bcolor3, fontSize: 12,
  },
  rolesView: {
    paddingLeft: 5,
    paddingRight: 5,
    ...st.fr,
    justifyContent: 'space-between',
  },
  rolesViewList: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginLeft: 5,
    marginRight: 5,
    overflow: 'hidden',
  },
  rolesTitleView: {
    height: 40,
    ...st.frcenter,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
  },
  roleIcon: {
    fontSize: 18,
    color: '#FC5E00',
    marginRight: 4,
  },
  roleText: {
    fontSize: 14,
    color: '#333',
  },
  rolesList: {
    height: 50,
    ...st.frcenter,
  },
  rolesImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 10,
  },
  lister: {
    margin: 10,
    backgroundColor: '#fff',
    ...st.fr,
    flexWrap: 'wrap',
  },
  list: {
    width: '25%',
    height: 70,
    ...st.jacenter,
  },
  listIcon: {
    fontSize: 24,
    color: Mcolor,
    marginBottom: 6,
  },
  listText: {
    fontSize: 12,
    color: '#333',
  },
});
export default styles;
