import { StyleSheet, Platform } from 'react-native';
import { Mcolor, st } from '../../utils';

const styles = StyleSheet.create({
  ...st,
  fixTop: {
    height: Platform.OS === 'ios' ? 99 : 79,
  },
  Headerleft: {
    height: 48,
    width: 20,
    ...st.jacenter,
  },
  HeaderRightText: {
    color: Mcolor,
    fontSize: 14,
    marginLeft: 10,
  },
  HeaderMain: {
    flex: 1,
    paddingLeft: 8,
    ...st.fr,
    ...st.jacenter,
    backgroundColor: '#eee',
    borderRadius: 5,
    marginLeft: 10,
    height: 30,
  },
  HeaderMainText: {
    color: '#999',
    fontSize: 14,
    flex: 1,
    marginLeft: 8,
  },
  conditions: {
    height: 35,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    backgroundColor: '#fff',
    ...st.fr,
  },
  cdsList: {
    flex: 1,
    ...st.fr,
    ...st.jacenter,
  },
  rightLine: {
    position: 'absolute',
    right: 0,
    top: 10,
    height: 15,
    width: 0.7,
    backgroundColor: '#ccc',
  },
  cddown: {
    color: '#666',
    fontSize: 12,
    marginLeft: 3,
  },
  cdsListText: {
    color: '#666',
    fontSize: 12,
  },
  mainView: {
    flex: 1,
    ...st.fr,
  },
  HeaderIcon: {
    color: '#666',
    fontSize: 18,
  },
  HeaderInput: {
    color: '#666',
    fontSize: 14,
    borderBottomColor: '#eee',
  },
  leftNav: {
    width: 90,
    backgroundColor: '#f2f2f2',
  },
  listContent: {
    flex: 1,
    backgroundColor: '#f2f2f2',
  },
  mainText: {
    color: '#555',
    fontSize: 14,
  },
  leftNavList: {
    height: 45,
    ...st.jacenter,
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    borderLeftColor: '#f2f2f2',
    borderRightColor: '#ccc',
    borderRightWidth: 1,
  },
  leftNavListCur: {
    borderLeftColor: Mcolor,
    borderRightColor: '#fff',
    backgroundColor: '#fff',
  },
  addressLeftList: {
    height: 45,
    ...st.jcenter,
    borderLeftWidth: 3,
    paddingLeft: 20,
    borderLeftColor: '#f2f2f2',
  },
  addressLeftListCur: {
    borderLeftColor: Mcolor,
    backgroundColor: '#f9f9f9',
  },
  addressRightList: {
    height: 45,
    paddingLeft: 20,
    ...st.jcenter,
  },
  leftNavText: {
    color: '#555',
    fontSize: 14,
  },
  leftNavTextCur: {
    color: Mcolor,
  },
  rightContent: {
    flex: 1,
    padding: 10,
    backgroundColor: '#fff',
  },
  rightAll: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginBottom: 10,
    ...st.jacenter,
    height: 35,
  },
  rightContentView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderLeftColor: '#ddd',
    borderLeftWidth: 1,
    borderTopColor: '#ddd',
    borderTopWidth: 1,
  },
  usedCityView: {
    flexWrap: 'wrap',
    height: 40,
    ...st.jcenter,
  },
  nousedCity: {
    paddingLeft: 10,
    color: '#888',
    fontSize: 14,
  },
  contetnTabView: {
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    borderRightColor: '#ddd',
    borderRightWidth: 1,
    height: 40,
    ...st.jacenter,
    width: `${100 / 3}%`,
  },
  maskerContentView: {
    ...st.fr,
    ...st.f1,
    flexWrap: 'wrap',
  },
  maskerBtns: {
    ...st.fr,
    height: 45,
    borderTopColor: '#ddd',
    borderTopWidth: 1,
  },
  maskerCancelBtn: {
    ...st.f1,
    ...st.jacenter,
    backgroundColor: '#fff',
  },
  maskerSaveBtn: {
    ...st.f1,
    ...st.jacenter,
    backgroundColor: Mcolor,
  },
  maskerBtnText: {
    fontSize: 16,
    color: '#666',
  },
  maskerBtnTextCur: {
    fontSize: 16,
    color: '#FFF',
  },
  maskerTitle: {
    backgroundColor: '#eee',
    paddingLeft: 10,
    height: 40,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    ...st.jcenter,
  },
  maskerTitleText: {
    fontSize: 14,
    color: '#444',
  },
  goodsDetail: {
    backgroundColor: '#fff',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 15,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  goodsName: {
    color: '#333',
    fontSize: 18,
    marginBottom: 10,
  },
  allText: {
    color: '#666',
    fontSize: 14,
  },
  goodsWeight: {
    flex: 1,
    justifyContent: 'flex-end',
    textAlign: 'right',
    color: '#FF7F12',
    fontSize: 18,
  },
  goodsVariety: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  goodsAddress: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  activeDetail: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  otherIndustryBox: {
    minHeight: 15,
    maxHeight: 15,
    backgroundColor: '#61BC3F',
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 3,
    marginBottom: 6,
  },
  otherIndustry: {
    color: '#fff',
    fontSize: 9,
    textAlign: 'center',
  },
  time: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  everyWeek: {
    color: '#FF7F12',
    borderWidth: 1,
    borderColor: '#FF7F12',
    borderRadius: 3,
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 8,
    paddingRight: 8,
    fontSize: 9,
    marginRight: 10,
  },
  scaleText: {
    color: '#666',
    fontSize: 11,
  },
  timeCount: {
    color: '#FF7F12',
  },
  offerBox: {
    width: 85,
    backgroundColor: '#FF7F12',
    paddingTop: 5,
    paddingBottom: 5,
    // paddingLeft: 10,
    // paddingRight: 10,
    borderRadius: 5,
  },
  offer: {
    fontSize: 16,
    color: '#fff',
    textAlign: 'center',
  },
});
export default styles;
