import { StyleSheet } from 'react-native';
import { Mcolor, st } from '../../utils';

const styles = StyleSheet.create({
  Headerleft: {
    height: 44,
    width: 26,
    ...st.jacenter,
  },
  HeaderMain: {
    flex: 1,
    paddingLeft: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eee',
    borderRadius: 5,
    marginLeft: 10,
    height: 30,
  },
  flexOne: {
    flex: 1,
  },
  mainView: {
    flex: 1,
    flexDirection: 'row',
  },
  HeaderIcon: {
    color: '#666',
    fontSize: 18,
  },
  HeaderInput: {
    color: '#666',
    fontSize: 14,
    borderBottomColor: '#eee',
  },
  leftNav: {
    width: 90,
    backgroundColor: '#f2f2f2',
  },
  mainText: {
    color: '#555',
    fontSize: 14,
  },
  leftNavList: {
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    borderLeftColor: '#f2f2f2',
    borderRightColor: '#ccc',
    borderRightWidth: 1,
  },
  leftNavListCur: {
    borderLeftColor: Mcolor,
    borderRightColor: '#fff',
    backgroundColor: '#fff',
  },
  leftNavText: {
    color: '#555',
    fontSize: 14,
  },
  leftNavTextCur: {
    color: Mcolor,
  },
  rightContent: {
    flex: 1,
    padding: 10,
    backgroundColor: '#fff',
  },
  rightAll: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    height: 35,
  },
  rightContentView: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderLeftColor: '#ddd',
    borderLeftWidth: 1,
    borderTopColor: '#ddd',
    borderTopWidth: 1,
  },
  contetnTabView: {
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
    borderRightColor: '#ddd',
    borderRightWidth: 1,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    minWidth: '30%',
  },
  listBox: {
    flex: 1,
    borderTopWidth: 1,
    paddingLeft: 10,
    paddingRight: 10,
    borderTopColor: '#eee',
    backgroundColor: '#fff',
  },
  myIcn: {
    fontSize: 12,
    color: '#666',
    marginLeft: 10,
    marginRight: 10,
  },
  myText: {
    fontSize: 14,
    color: '#666',
  },
  flexBox: {
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  flexRow: {
    paddingTop: 15,
    paddingBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  historyBox: {
    // width,
    paddingTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: '#fff',
  },
  flexRowBox: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  chooseBtn: {
    height: 35,
    ...st.jacenter,
    paddingLeft: 10,
    paddingRight: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 5,
    marginBottom: 8,
  },
  okBtn: {
    height: 26,
    ...st.jacenter,
    paddingLeft: 6,
    paddingRight: 6,
    borderRadius: 5,
    backgroundColor: Mcolor,
  },
  okBtnText: {
    fontSize: 14,
    color: '#fff',
  },
  btnText: {
    fontSize: 14,
    color: '#666',
  },
});
export default styles;
